version: 2
updates:
  - package-ecosystem: gomod
    directory: /plugins/kyverno
    schedule:
      interval: daily
  - package-ecosystem: gomod
    directory: /plugins/trivy
    schedule:
      interval: daily
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
